/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Authentification (void);
GtkWidget* create_principale (void);
GtkWidget* create_Ajout (void);
GtkWidget* create_Modification (void);
GtkWidget* create_Calcul (void);
GtkWidget* create_Recherche (void);
