/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Authentification (void)
{
  GtkWidget *Authentification;
  GtkWidget *fixed1;
  GtkWidget *labelnom_auth;
  GtkWidget *labelloginauth;
  GtkWidget *entry_nomauth;
  GtkWidget *entry_mdpauth;
  GtkWidget *Espace_authentification;
  GtkWidget *Valider_auth;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label5;

  Authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Authentification), _("Authentification"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Authentification), fixed1);

  labelnom_auth = gtk_label_new (_("NOM:"));
  gtk_widget_show (labelnom_auth);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnom_auth, 32, 112);
  gtk_widget_set_size_request (labelnom_auth, 75, 30);

  labelloginauth = gtk_label_new (_("MOT DE PASSE:"));
  gtk_widget_show (labelloginauth);
  gtk_fixed_put (GTK_FIXED (fixed1), labelloginauth, 16, 184);
  gtk_widget_set_size_request (labelloginauth, 129, 17);

  entry_nomauth = gtk_entry_new ();
  gtk_widget_show (entry_nomauth);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nomauth, 144, 112);
  gtk_widget_set_size_request (entry_nomauth, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomauth), 8226);

  entry_mdpauth = gtk_entry_new ();
  gtk_widget_show (entry_mdpauth);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_mdpauth, 144, 176);
  gtk_widget_set_size_request (entry_mdpauth, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mdpauth), 8226);

  Espace_authentification = gtk_label_new (_("AUTHENTIFICATION"));
  gtk_widget_show (Espace_authentification);
  gtk_fixed_put (GTK_FIXED (fixed1), Espace_authentification, 96, 16);
  gtk_widget_set_size_request (Espace_authentification, 199, 84);
  gtk_misc_set_alignment (GTK_MISC (Espace_authentification), 0.5, 0.49);
  gtk_label_set_width_chars (GTK_LABEL (Espace_authentification), 3);

  Valider_auth = gtk_button_new ();
  gtk_widget_show (Valider_auth);
  gtk_fixed_put (GTK_FIXED (fixed1), Valider_auth, 177, 250);
  gtk_widget_set_size_request (Valider_auth, 92, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Valider_auth), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Valider_auth, "clicked",
                    G_CALLBACK (on_Valider_auth_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Authentification, Authentification, "Authentification");
  GLADE_HOOKUP_OBJECT (Authentification, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Authentification, labelnom_auth, "labelnom_auth");
  GLADE_HOOKUP_OBJECT (Authentification, labelloginauth, "labelloginauth");
  GLADE_HOOKUP_OBJECT (Authentification, entry_nomauth, "entry_nomauth");
  GLADE_HOOKUP_OBJECT (Authentification, entry_mdpauth, "entry_mdpauth");
  GLADE_HOOKUP_OBJECT (Authentification, Espace_authentification, "Espace_authentification");
  GLADE_HOOKUP_OBJECT (Authentification, Valider_auth, "Valider_auth");
  GLADE_HOOKUP_OBJECT (Authentification, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Authentification, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Authentification, image1, "image1");
  GLADE_HOOKUP_OBJECT (Authentification, label5, "label5");

  return Authentification;
}

GtkWidget*
create_principale (void)
{
  GtkWidget *principale;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *entry_idsuppression;
  GtkWidget *button_Ajout;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *button_modification;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *Suppress;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label36;
  GtkWidget *Espace_agent;
  GtkWidget *button_Affichage;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label25;
  GtkWidget *button_calcul;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label11;
  GtkWidget *button_recherche;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label10;

  principale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (principale), _("principale"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (principale), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 8, 48);
  gtk_widget_set_size_request (treeview1, 576, 280);

  entry_idsuppression = gtk_entry_new ();
  gtk_widget_show (entry_idsuppression);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_idsuppression, 608, 224);
  gtk_widget_set_size_request (entry_idsuppression, 128, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idsuppression), 8226);

  button_Ajout = gtk_button_new ();
  gtk_widget_show (button_Ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), button_Ajout, 608, 96);
  gtk_widget_set_size_request (button_Ajout, 125, 45);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_Ajout), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Ajout"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  button_modification = gtk_button_new ();
  gtk_widget_show (button_modification);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modification, 608, 160);
  gtk_widget_set_size_request (button_modification, 129, 47);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_modification), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Modification"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  Suppress = gtk_button_new ();
  gtk_widget_show (Suppress);
  gtk_fixed_put (GTK_FIXED (fixed2), Suppress, 608, 272);
  gtk_widget_set_size_request (Suppress, 128, 53);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (Suppress), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("suppression"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox17), label36, FALSE, FALSE, 0);

  Espace_agent = gtk_label_new (_("ESPACE AGENT"));
  gtk_widget_show (Espace_agent);
  gtk_fixed_put (GTK_FIXED (fixed2), Espace_agent, 168, 0);
  gtk_widget_set_size_request (Espace_agent, 132, 72);

  button_Affichage = gtk_button_new ();
  gtk_widget_show (button_Affichage);
  gtk_fixed_put (GTK_FIXED (fixed2), button_Affichage, 320, 328);
  gtk_widget_set_size_request (button_Affichage, 112, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_Affichage), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("AFFICHAGE"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox11), label25, FALSE, FALSE, 0);

  button_calcul = gtk_button_new ();
  gtk_widget_show (button_calcul);
  gtk_fixed_put (GTK_FIXED (fixed2), button_calcul, 192, 328);
  gtk_widget_set_size_request (button_calcul, 112, 45);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_calcul), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Calcul"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox6), label11, FALSE, FALSE, 0);

  button_recherche = gtk_button_new ();
  gtk_widget_show (button_recherche);
  gtk_fixed_put (GTK_FIXED (fixed2), button_recherche, 64, 328);
  gtk_widget_set_size_request (button_recherche, 112, 45);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_recherche), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_Ajout, "clicked",
                    G_CALLBACK (on_button_Ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modification, "clicked",
                    G_CALLBACK (on_button_modification_clicked),
                    NULL);
  g_signal_connect ((gpointer) Suppress, "clicked",
                    G_CALLBACK (on_Suppress_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Affichage, "clicked",
                    G_CALLBACK (on_button_Affichage_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_calcul, "clicked",
                    G_CALLBACK (on_button_calcul_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_recherche, "clicked",
                    G_CALLBACK (on_button_recherche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (principale, principale, "principale");
  GLADE_HOOKUP_OBJECT (principale, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (principale, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (principale, entry_idsuppression, "entry_idsuppression");
  GLADE_HOOKUP_OBJECT (principale, button_Ajout, "button_Ajout");
  GLADE_HOOKUP_OBJECT (principale, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (principale, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (principale, image3, "image3");
  GLADE_HOOKUP_OBJECT (principale, label8, "label8");
  GLADE_HOOKUP_OBJECT (principale, button_modification, "button_modification");
  GLADE_HOOKUP_OBJECT (principale, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (principale, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (principale, image2, "image2");
  GLADE_HOOKUP_OBJECT (principale, label7, "label7");
  GLADE_HOOKUP_OBJECT (principale, Suppress, "Suppress");
  GLADE_HOOKUP_OBJECT (principale, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (principale, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (principale, image17, "image17");
  GLADE_HOOKUP_OBJECT (principale, label36, "label36");
  GLADE_HOOKUP_OBJECT (principale, Espace_agent, "Espace_agent");
  GLADE_HOOKUP_OBJECT (principale, button_Affichage, "button_Affichage");
  GLADE_HOOKUP_OBJECT (principale, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (principale, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (principale, image11, "image11");
  GLADE_HOOKUP_OBJECT (principale, label25, "label25");
  GLADE_HOOKUP_OBJECT (principale, button_calcul, "button_calcul");
  GLADE_HOOKUP_OBJECT (principale, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (principale, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (principale, image6, "image6");
  GLADE_HOOKUP_OBJECT (principale, label11, "label11");
  GLADE_HOOKUP_OBJECT (principale, button_recherche, "button_recherche");
  GLADE_HOOKUP_OBJECT (principale, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (principale, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (principale, image5, "image5");
  GLADE_HOOKUP_OBJECT (principale, label10, "label10");

  return principale;
}

GtkWidget*
create_Ajout (void)
{
  GtkWidget *Ajout;
  GtkWidget *fixed3;
  GtkWidget *entry_nomajout;
  GtkWidget *entry_prenomajout;
  GtkObject *spinbutton_ajout_adj;
  GtkWidget *spinbutton_ajout;
  GtkObject *spinbutton_mois_adj;
  GtkWidget *spinbutton_mois;
  GtkObject *spinbutton_annee_adj;
  GtkWidget *spinbutton_annee;
  GtkWidget *entry_id;
  GtkWidget *entry_chambreajout;
  GtkWidget *radiobutton_m;
  GSList *radiobutton_m_group = NULL;
  GtkWidget *button_ajouter;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label18;
  GtkWidget *button_retour_ajout;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label24;
  GtkWidget *label_nomajout;
  GtkWidget *label_ajoutprenom;
  GtkWidget *label_jour;
  GtkWidget *label_ddnajout;
  GtkWidget *label_mois;
  GtkWidget *label_annee;
  GtkWidget *label_classe;
  GtkWidget *combobox_classe;
  GtkWidget *label_id;
  GtkWidget *label_chambreajout;
  GtkWidget *label_sexe;
  GtkWidget *radiobutton_f;
  GtkWidget *labelajout;

  Ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout), _("Ajout"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Ajout), fixed3);

  entry_nomajout = gtk_entry_new ();
  gtk_widget_show (entry_nomajout);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_nomajout, 72, 136);
  gtk_widget_set_size_request (entry_nomajout, 176, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomajout), 8226);

  entry_prenomajout = gtk_entry_new ();
  gtk_widget_show (entry_prenomajout);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_prenomajout, 328, 136);
  gtk_widget_set_size_request (entry_prenomajout, 176, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenomajout), 8226);

  spinbutton_ajout_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_ajout_adj), 1, 0);
  gtk_widget_show (spinbutton_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_ajout, 184, 192);
  gtk_widget_set_size_request (spinbutton_ajout, 56, 27);

  spinbutton_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_adj), 1, 0);
  gtk_widget_show (spinbutton_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_mois, 288, 192);
  gtk_widget_set_size_request (spinbutton_mois, 60, 27);

  spinbutton_annee_adj = gtk_adjustment_new (1, 1980, 2006, 1, 10, 10);
  spinbutton_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_annee_adj), 1, 0);
  gtk_widget_show (spinbutton_annee);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_annee, 400, 192);
  gtk_widget_set_size_request (spinbutton_annee, 60, 27);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_id, 248, 256);
  gtk_widget_set_size_request (entry_id, 120, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_chambreajout = gtk_entry_new ();
  gtk_widget_show (entry_chambreajout);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_chambreajout, 496, 256);
  gtk_widget_set_size_request (entry_chambreajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_chambreajout), 8226);

  radiobutton_m = gtk_radio_button_new_with_mnemonic (NULL, _("M"));
  gtk_widget_show (radiobutton_m);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton_m, 56, 328);
  gtk_widget_set_size_request (radiobutton_m, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_m), radiobutton_m_group);
  radiobutton_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_m));

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), button_ajouter, 112, 408);
  gtk_widget_set_size_request (button_ajouter, 112, 69);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox7), label18, FALSE, FALSE, 0);

  button_retour_ajout = gtk_button_new ();
  gtk_widget_show (button_retour_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), button_retour_ajout, 224, 408);
  gtk_widget_set_size_request (button_retour_ajout, 120, 69);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_retour_ajout), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("RETOUR"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox10), label24, FALSE, FALSE, 0);

  label_nomajout = gtk_label_new (_("NOM:"));
  gtk_widget_show (label_nomajout);
  gtk_fixed_put (GTK_FIXED (fixed3), label_nomajout, 0, 128);
  gtk_widget_set_size_request (label_nomajout, 84, 43);

  label_ajoutprenom = gtk_label_new (_("PRENOM:"));
  gtk_widget_show (label_ajoutprenom);
  gtk_fixed_put (GTK_FIXED (fixed3), label_ajoutprenom, 248, 128);
  gtk_widget_set_size_request (label_ajoutprenom, 75, 39);

  label_jour = gtk_label_new (_("jour:"));
  gtk_widget_show (label_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), label_jour, 144, 200);
  gtk_widget_set_size_request (label_jour, 49, 17);

  label_ddnajout = gtk_label_new (_("DATE_NAISSANCE:"));
  gtk_widget_show (label_ddnajout);
  gtk_fixed_put (GTK_FIXED (fixed3), label_ddnajout, 0, 192);
  gtk_widget_set_size_request (label_ddnajout, 152, 33);

  label_mois = gtk_label_new (_("mois:"));
  gtk_widget_show (label_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), label_mois, 240, 200);
  gtk_widget_set_size_request (label_mois, 49, 17);

  label_annee = gtk_label_new (_("annee:"));
  gtk_widget_show (label_annee);
  gtk_fixed_put (GTK_FIXED (fixed3), label_annee, 352, 200);
  gtk_widget_set_size_request (label_annee, 49, 17);

  label_classe = gtk_label_new (_("CLASSE:"));
  gtk_widget_show (label_classe);
  gtk_fixed_put (GTK_FIXED (fixed3), label_classe, 8, 256);
  gtk_widget_set_size_request (label_classe, 72, 25);

  combobox_classe = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_classe);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox_classe, 80, 248);
  gtk_widget_set_size_request (combobox_classe, 54, 36);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classe), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classe), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classe), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classe), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classe), _("5"));

  label_id = gtk_label_new (_("IDENTIFIANT:"));
  gtk_widget_show (label_id);
  gtk_fixed_put (GTK_FIXED (fixed3), label_id, 144, 256);
  gtk_widget_set_size_request (label_id, 107, 22);

  label_chambreajout = gtk_label_new (_("CHAMBRE:"));
  gtk_widget_show (label_chambreajout);
  gtk_fixed_put (GTK_FIXED (fixed3), label_chambreajout, 392, 256);
  gtk_widget_set_size_request (label_chambreajout, 96, 33);

  label_sexe = gtk_label_new (_("SEXE:"));
  gtk_widget_show (label_sexe);
  gtk_fixed_put (GTK_FIXED (fixed3), label_sexe, 8, 328);
  gtk_widget_set_size_request (label_sexe, 64, 25);

  radiobutton_f = gtk_radio_button_new_with_mnemonic (NULL, _("F"));
  gtk_widget_show (radiobutton_f);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton_f, 128, 328);
  gtk_widget_set_size_request (radiobutton_f, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_f), radiobutton_m_group);
  radiobutton_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_f));

  labelajout = gtk_label_new ("");
  gtk_widget_show (labelajout);
  gtk_fixed_put (GTK_FIXED (fixed3), labelajout, 488, 304);
  gtk_widget_set_size_request (labelajout, 160, 81);

  g_signal_connect ((gpointer) radiobutton_m, "toggled",
                    G_CALLBACK (on_radiobutton_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_ajout, "clicked",
                    G_CALLBACK (on_button_retour_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_f, "toggled",
                    G_CALLBACK (on_radiobutton_f_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (Ajout, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Ajout, entry_nomajout, "entry_nomajout");
  GLADE_HOOKUP_OBJECT (Ajout, entry_prenomajout, "entry_prenomajout");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton_ajout, "spinbutton_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton_mois, "spinbutton_mois");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton_annee, "spinbutton_annee");
  GLADE_HOOKUP_OBJECT (Ajout, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (Ajout, entry_chambreajout, "entry_chambreajout");
  GLADE_HOOKUP_OBJECT (Ajout, radiobutton_m, "radiobutton_m");
  GLADE_HOOKUP_OBJECT (Ajout, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Ajout, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Ajout, image7, "image7");
  GLADE_HOOKUP_OBJECT (Ajout, label18, "label18");
  GLADE_HOOKUP_OBJECT (Ajout, button_retour_ajout, "button_retour_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Ajout, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Ajout, image10, "image10");
  GLADE_HOOKUP_OBJECT (Ajout, label24, "label24");
  GLADE_HOOKUP_OBJECT (Ajout, label_nomajout, "label_nomajout");
  GLADE_HOOKUP_OBJECT (Ajout, label_ajoutprenom, "label_ajoutprenom");
  GLADE_HOOKUP_OBJECT (Ajout, label_jour, "label_jour");
  GLADE_HOOKUP_OBJECT (Ajout, label_ddnajout, "label_ddnajout");
  GLADE_HOOKUP_OBJECT (Ajout, label_mois, "label_mois");
  GLADE_HOOKUP_OBJECT (Ajout, label_annee, "label_annee");
  GLADE_HOOKUP_OBJECT (Ajout, label_classe, "label_classe");
  GLADE_HOOKUP_OBJECT (Ajout, combobox_classe, "combobox_classe");
  GLADE_HOOKUP_OBJECT (Ajout, label_id, "label_id");
  GLADE_HOOKUP_OBJECT (Ajout, label_chambreajout, "label_chambreajout");
  GLADE_HOOKUP_OBJECT (Ajout, label_sexe, "label_sexe");
  GLADE_HOOKUP_OBJECT (Ajout, radiobutton_f, "radiobutton_f");
  GLADE_HOOKUP_OBJECT (Ajout, labelajout, "labelajout");

  return Ajout;
}

GtkWidget*
create_Modification (void)
{
  GtkWidget *Modification;
  GtkWidget *fixed4;
  GtkWidget *entry_idmodif;
  GtkWidget *entry_chambremodif;
  GtkWidget *entrynomodif;
  GtkWidget *entryprenmodif;
  GtkObject *spinbuttonj_adj;
  GtkWidget *spinbuttonj;
  GtkObject *spinbuttonm_adj;
  GtkWidget *spinbuttonm;
  GtkObject *spinbuttona_adj;
  GtkWidget *spinbuttona;
  GtkWidget *labelnommodif;
  GtkWidget *labelprenmodif;
  GtkWidget *labelm;
  GtkWidget *labelan;
  GtkWidget *label_classemodif;
  GtkWidget *label_idmodif;
  GtkWidget *button_retourmodif;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label23;
  GtkWidget *labelsex;
  GtkWidget *labelddnmodif;
  GtkWidget *label_chambremodif;
  GtkWidget *labelj;
  GtkWidget *combobox_classemodif;
  GtkWidget *radiobutton_mm;
  GSList *radiobutton_mm_group = NULL;
  GtkWidget *radiobuttonfm;
  GtkWidget *button_modif;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label22;
  GtkWidget *labelmodif;

  Modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modification), _("Modification"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Modification), fixed4);

  entry_idmodif = gtk_entry_new ();
  gtk_widget_show (entry_idmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_idmodif, 336, 160);
  gtk_widget_set_size_request (entry_idmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idmodif), 8226);

  entry_chambremodif = gtk_entry_new ();
  gtk_widget_show (entry_chambremodif);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_chambremodif, 672, 160);
  gtk_widget_set_size_request (entry_chambremodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_chambremodif), 8226);

  entrynomodif = gtk_entry_new ();
  gtk_widget_show (entrynomodif);
  gtk_fixed_put (GTK_FIXED (fixed4), entrynomodif, 88, 56);
  gtk_widget_set_size_request (entrynomodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomodif), 8226);

  entryprenmodif = gtk_entry_new ();
  gtk_widget_show (entryprenmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), entryprenmodif, 344, 56);
  gtk_widget_set_size_request (entryprenmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenmodif), 8226);

  spinbuttonj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonj_adj), 1, 0);
  gtk_widget_show (spinbuttonj);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonj, 168, 104);
  gtk_widget_set_size_request (spinbuttonj, 60, 27);

  spinbuttonm_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonm_adj), 1, 0);
  gtk_widget_show (spinbuttonm);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonm, 272, 104);
  gtk_widget_set_size_request (spinbuttonm, 60, 27);

  spinbuttona_adj = gtk_adjustment_new (1, 1990, 2006, 1, 10, 10);
  spinbuttona = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttona_adj), 1, 0);
  gtk_widget_show (spinbuttona);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttona, 384, 104);
  gtk_widget_set_size_request (spinbuttona, 60, 27);

  labelnommodif = gtk_label_new (_("NOM:"));
  gtk_widget_show (labelnommodif);
  gtk_fixed_put (GTK_FIXED (fixed4), labelnommodif, 16, 56);
  gtk_widget_set_size_request (labelnommodif, 72, 25);

  labelprenmodif = gtk_label_new (_("PRENOM:"));
  gtk_widget_show (labelprenmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), labelprenmodif, 264, 48);
  gtk_widget_set_size_request (labelprenmodif, 80, 41);

  labelm = gtk_label_new (_("mois:"));
  gtk_widget_show (labelm);
  gtk_fixed_put (GTK_FIXED (fixed4), labelm, 224, 104);
  gtk_widget_set_size_request (labelm, 48, 25);

  labelan = gtk_label_new (_("annee:"));
  gtk_widget_show (labelan);
  gtk_fixed_put (GTK_FIXED (fixed4), labelan, 328, 104);
  gtk_widget_set_size_request (labelan, 56, 25);

  label_classemodif = gtk_label_new (_("NOUVELLE CLASSE:"));
  gtk_widget_show (label_classemodif);
  gtk_fixed_put (GTK_FIXED (fixed4), label_classemodif, 0, 160);
  gtk_widget_set_size_request (label_classemodif, 160, 33);

  label_idmodif = gtk_label_new (_("IDENTIFIANT:"));
  gtk_widget_show (label_idmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), label_idmodif, 240, 144);
  gtk_widget_set_size_request (label_idmodif, 104, 56);

  button_retourmodif = gtk_button_new ();
  gtk_widget_show (button_retourmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), button_retourmodif, 192, 280);
  gtk_widget_set_size_request (button_retourmodif, 104, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_retourmodif), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("RETOUR"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox9), label23, FALSE, FALSE, 0);

  labelsex = gtk_label_new (_("SEXE:"));
  gtk_widget_show (labelsex);
  gtk_fixed_put (GTK_FIXED (fixed4), labelsex, 24, 224);
  gtk_widget_set_size_request (labelsex, 64, 33);

  labelddnmodif = gtk_label_new (_("Date_naissance:"));
  gtk_widget_show (labelddnmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), labelddnmodif, 0, 104);
  gtk_widget_set_size_request (labelddnmodif, 128, 25);

  label_chambremodif = gtk_label_new (_("NOUVELLE CHAMBRE:"));
  gtk_widget_show (label_chambremodif);
  gtk_fixed_put (GTK_FIXED (fixed4), label_chambremodif, 504, 160);
  gtk_widget_set_size_request (label_chambremodif, 160, 32);

  labelj = gtk_label_new (_("jour:"));
  gtk_widget_show (labelj);
  gtk_fixed_put (GTK_FIXED (fixed4), labelj, 120, 104);
  gtk_widget_set_size_request (labelj, 56, 24);

  combobox_classemodif = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_classemodif);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox_classemodif, 152, 160);
  gtk_widget_set_size_request (combobox_classemodif, 72, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classemodif), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classemodif), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classemodif), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classemodif), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_classemodif), _("5"));

  radiobutton_mm = gtk_radio_button_new_with_mnemonic (NULL, _("M"));
  gtk_widget_show (radiobutton_mm);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_mm, 88, 232);
  gtk_widget_set_size_request (radiobutton_mm, 112, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mm), radiobutton_mm_group);
  radiobutton_mm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mm));

  radiobuttonfm = gtk_radio_button_new_with_mnemonic (NULL, _("F"));
  gtk_widget_show (radiobuttonfm);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobuttonfm, 144, 232);
  gtk_widget_set_size_request (radiobuttonfm, 128, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfm), radiobutton_mm_group);
  radiobutton_mm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfm));

  button_modif = gtk_button_new ();
  gtk_widget_show (button_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), button_modif, 72, 280);
  gtk_widget_set_size_request (button_modif, 112, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_modif), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("MODIFIER"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox8), label22, FALSE, FALSE, 0);

  labelmodif = gtk_label_new ("");
  gtk_widget_show (labelmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), labelmodif, 456, 216);
  gtk_widget_set_size_request (labelmodif, 176, 64);

  g_signal_connect ((gpointer) button_retourmodif, "clicked",
                    G_CALLBACK (on_button_retourmodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mm, "toggled",
                    G_CALLBACK (on_radiobutton_mm_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonfm, "toggled",
                    G_CALLBACK (on_radiobuttonfm_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_modif, "clicked",
                    G_CALLBACK (on_button_modif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modification, Modification, "Modification");
  GLADE_HOOKUP_OBJECT (Modification, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Modification, entry_idmodif, "entry_idmodif");
  GLADE_HOOKUP_OBJECT (Modification, entry_chambremodif, "entry_chambremodif");
  GLADE_HOOKUP_OBJECT (Modification, entrynomodif, "entrynomodif");
  GLADE_HOOKUP_OBJECT (Modification, entryprenmodif, "entryprenmodif");
  GLADE_HOOKUP_OBJECT (Modification, spinbuttonj, "spinbuttonj");
  GLADE_HOOKUP_OBJECT (Modification, spinbuttonm, "spinbuttonm");
  GLADE_HOOKUP_OBJECT (Modification, spinbuttona, "spinbuttona");
  GLADE_HOOKUP_OBJECT (Modification, labelnommodif, "labelnommodif");
  GLADE_HOOKUP_OBJECT (Modification, labelprenmodif, "labelprenmodif");
  GLADE_HOOKUP_OBJECT (Modification, labelm, "labelm");
  GLADE_HOOKUP_OBJECT (Modification, labelan, "labelan");
  GLADE_HOOKUP_OBJECT (Modification, label_classemodif, "label_classemodif");
  GLADE_HOOKUP_OBJECT (Modification, label_idmodif, "label_idmodif");
  GLADE_HOOKUP_OBJECT (Modification, button_retourmodif, "button_retourmodif");
  GLADE_HOOKUP_OBJECT (Modification, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Modification, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Modification, image9, "image9");
  GLADE_HOOKUP_OBJECT (Modification, label23, "label23");
  GLADE_HOOKUP_OBJECT (Modification, labelsex, "labelsex");
  GLADE_HOOKUP_OBJECT (Modification, labelddnmodif, "labelddnmodif");
  GLADE_HOOKUP_OBJECT (Modification, label_chambremodif, "label_chambremodif");
  GLADE_HOOKUP_OBJECT (Modification, labelj, "labelj");
  GLADE_HOOKUP_OBJECT (Modification, combobox_classemodif, "combobox_classemodif");
  GLADE_HOOKUP_OBJECT (Modification, radiobutton_mm, "radiobutton_mm");
  GLADE_HOOKUP_OBJECT (Modification, radiobuttonfm, "radiobuttonfm");
  GLADE_HOOKUP_OBJECT (Modification, button_modif, "button_modif");
  GLADE_HOOKUP_OBJECT (Modification, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Modification, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Modification, image8, "image8");
  GLADE_HOOKUP_OBJECT (Modification, label22, "label22");
  GLADE_HOOKUP_OBJECT (Modification, labelmodif, "labelmodif");

  return Modification;
}

GtkWidget*
create_Calcul (void)
{
  GtkWidget *Calcul;
  GtkWidget *fixed5;
  GtkWidget *label26;
  GtkWidget *checkbutton_d;
  GtkWidget *checkbutton_t;
  GtkWidget *checkbutton_q;
  GtkWidget *checkbutton_c;
  GtkWidget *checkbutton_p;
  GtkWidget *button_retourcalcul;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label32;
  GtkWidget *button_calculer;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label27;
  GtkWidget *label38;
  GtkWidget *label_calcul_s;

  Calcul = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Calcul), _("Calcul"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Calcul), fixed5);

  label26 = gtk_label_new (_("CLASSE:"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 0, 120);
  gtk_widget_set_size_request (label26, 80, 60);

  checkbutton_d = gtk_check_button_new_with_mnemonic (_("2\303\250me"));
  gtk_widget_show (checkbutton_d);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_d, 144, 136);
  gtk_widget_set_size_request (checkbutton_d, 64, 24);

  checkbutton_t = gtk_check_button_new_with_mnemonic (_("3\303\250me"));
  gtk_widget_show (checkbutton_t);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_t, 208, 136);
  gtk_widget_set_size_request (checkbutton_t, 72, 24);

  checkbutton_q = gtk_check_button_new_with_mnemonic (_("4 \303\250me"));
  gtk_widget_show (checkbutton_q);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_q, 280, 136);
  gtk_widget_set_size_request (checkbutton_q, 72, 24);

  checkbutton_c = gtk_check_button_new_with_mnemonic (_("5\303\250me"));
  gtk_widget_show (checkbutton_c);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_c, 352, 136);
  gtk_widget_set_size_request (checkbutton_c, 72, 24);

  checkbutton_p = gtk_check_button_new_with_mnemonic (_("1\303\250re"));
  gtk_widget_show (checkbutton_p);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_p, 80, 136);
  gtk_widget_set_size_request (checkbutton_p, 56, 24);

  button_retourcalcul = gtk_button_new ();
  gtk_widget_show (button_retourcalcul);
  gtk_fixed_put (GTK_FIXED (fixed5), button_retourcalcul, 200, 224);
  gtk_widget_set_size_request (button_retourcalcul, 112, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_retourcalcul), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox15), label32, FALSE, FALSE, 0);

  button_calculer = gtk_button_new ();
  gtk_widget_show (button_calculer);
  gtk_fixed_put (GTK_FIXED (fixed5), button_calculer, 88, 224);
  gtk_widget_set_size_request (button_calculer, 112, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_calculer), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("CALCULER"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox12), label27, FALSE, FALSE, 0);

  label38 = gtk_label_new (_("Le nombre est:"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 48, 176);
  gtk_widget_set_size_request (label38, 168, 33);

  label_calcul_s = gtk_label_new ("");
  gtk_widget_show (label_calcul_s);
  gtk_fixed_put (GTK_FIXED (fixed5), label_calcul_s, 184, 168);
  gtk_widget_set_size_request (label_calcul_s, 80, 47);

  g_signal_connect ((gpointer) checkbutton_d, "toggled",
                    G_CALLBACK (on_checkbutton_d_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_t, "toggled",
                    G_CALLBACK (on_checkbutton_t_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_q, "toggled",
                    G_CALLBACK (on_checkbutton_q_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_c, "toggled",
                    G_CALLBACK (on_checkbutton_c_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_p, "toggled",
                    G_CALLBACK (on_checkbutton_p_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_retourcalcul, "clicked",
                    G_CALLBACK (on_button_retourcalcul_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_calculer, "clicked",
                    G_CALLBACK (on_button_calculer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Calcul, Calcul, "Calcul");
  GLADE_HOOKUP_OBJECT (Calcul, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Calcul, label26, "label26");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_d, "checkbutton_d");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_t, "checkbutton_t");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_q, "checkbutton_q");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_c, "checkbutton_c");
  GLADE_HOOKUP_OBJECT (Calcul, checkbutton_p, "checkbutton_p");
  GLADE_HOOKUP_OBJECT (Calcul, button_retourcalcul, "button_retourcalcul");
  GLADE_HOOKUP_OBJECT (Calcul, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Calcul, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Calcul, image15, "image15");
  GLADE_HOOKUP_OBJECT (Calcul, label32, "label32");
  GLADE_HOOKUP_OBJECT (Calcul, button_calculer, "button_calculer");
  GLADE_HOOKUP_OBJECT (Calcul, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Calcul, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Calcul, image12, "image12");
  GLADE_HOOKUP_OBJECT (Calcul, label27, "label27");
  GLADE_HOOKUP_OBJECT (Calcul, label38, "label38");
  GLADE_HOOKUP_OBJECT (Calcul, label_calcul_s, "label_calcul_s");

  return Calcul;
}

GtkWidget*
create_Recherche (void)
{
  GtkWidget *Recherche;
  GtkWidget *fixed6;
  GtkWidget *entry_idrecherche;
  GtkWidget *button_rechercher;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label29;
  GtkWidget *button_retourrecherche;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label30;
  GtkWidget *label28;
  GtkWidget *labeltrouve;

  Recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Recherche), _("Recherche"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Recherche), fixed6);

  entry_idrecherche = gtk_entry_new ();
  gtk_widget_show (entry_idrecherche);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_idrecherche, 168, 56);
  gtk_widget_set_size_request (entry_idrecherche, 168, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idrecherche), 8226);

  button_rechercher = gtk_button_new ();
  gtk_widget_show (button_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed6), button_rechercher, 48, 176);
  gtk_widget_set_size_request (button_rechercher, 128, 45);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_rechercher), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox13), label29, FALSE, FALSE, 0);

  button_retourrecherche = gtk_button_new ();
  gtk_widget_show (button_retourrecherche);
  gtk_fixed_put (GTK_FIXED (fixed6), button_retourrecherche, 200, 176);
  gtk_widget_set_size_request (button_retourrecherche, 144, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_retourrecherche), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("RETOUR"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox14), label30, FALSE, FALSE, 0);

  label28 = gtk_label_new (_("IDENTIFIANT:"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 24, 40);
  gtk_widget_set_size_request (label28, 128, 57);

  labeltrouve = gtk_label_new ("");
  gtk_widget_show (labeltrouve);
  gtk_fixed_put (GTK_FIXED (fixed6), labeltrouve, 88, 96);
  gtk_widget_set_size_request (labeltrouve, 192, 57);
  gtk_misc_set_alignment (GTK_MISC (labeltrouve), 0.5, 0.51);

  g_signal_connect ((gpointer) button_rechercher, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourrecherche, "clicked",
                    G_CALLBACK (on_button_retourrecherche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Recherche, Recherche, "Recherche");
  GLADE_HOOKUP_OBJECT (Recherche, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Recherche, entry_idrecherche, "entry_idrecherche");
  GLADE_HOOKUP_OBJECT (Recherche, button_rechercher, "button_rechercher");
  GLADE_HOOKUP_OBJECT (Recherche, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Recherche, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Recherche, image13, "image13");
  GLADE_HOOKUP_OBJECT (Recherche, label29, "label29");
  GLADE_HOOKUP_OBJECT (Recherche, button_retourrecherche, "button_retourrecherche");
  GLADE_HOOKUP_OBJECT (Recherche, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Recherche, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Recherche, image14, "image14");
  GLADE_HOOKUP_OBJECT (Recherche, label30, "label30");
  GLADE_HOOKUP_OBJECT (Recherche, label28, "label28");
  GLADE_HOOKUP_OBJECT (Recherche, labeltrouve, "labeltrouve");

  return Recherche;
}

